#ifndef MAGEQUEST_SRC_RESOURCES_FONTSTORAGE_H_
#define MAGEQUEST_SRC_RESOURCES_FONTSTORAGE_H_


inline Font ANT_PARTY;
inline Font VARNISHED;
inline Font MINECRAFT_BOLD;


#endif  //MAGEQUEST_SRC_RESOURCES_FONTSTORAGE_H_
