#ifndef MAGEQUEST_SRC_RESOURCES_FONTSTORAGE_H_
#define MAGEQUEST_SRC_RESOURCES_FONTSTORAGE_H_


inline Font ANT_PARTY;
inline Font VARNISHED;
inline Font MINECRAFT_BOLD;
inline Font MINECRAFT_ITALIC;
inline Font MINECRAFT_REGULAR;
inline Font EDIT_UNDO;
inline Font MINIMAL_PIXEL;

#endif  //MAGEQUEST_SRC_RESOURCES_FONTSTORAGE_H_
