#ifndef DUNGEONM_SRC_UTIL_GLOBALVARIABLES_H_
#define DUNGEONM_SRC_UTIL_GLOBALVARIABLES_H_

inline int SCREEN_WIDTH = 1280;
inline int SCREEN_HEIGHT = 960;
inline float UI_SCALE = 1;
#endif  //DUNGEONM_SRC_UTIL_GLOBALVARIABLES_H_
