#ifndef MAGEQUEST_SRC_QUEST_QUESTSTORAGE_H_
#define MAGEQUEST_SRC_QUEST_QUESTSTORAGE_H_
namespace Quests{
Quest* TUTORIAL;
Quest* MARLA_LOST_NECKLACE;
Quest* START_SOMETHING_NEW;
Quest* HILLCREST_PUZZLE;
Quest* NIETZSCHE;
Quest* THE_GROVES_SECRET;
}
#endif  //MAGEQUEST_SRC_QUEST_QUESTSTORAGE_H_
