#ifndef MAGEQUEST_SRC_GAMESTATEIO_LOADING_LOADERS_GAMEINFOLOADER_H_
#define MAGEQUEST_SRC_GAMESTATEIO_LOADING_LOADERS_GAMEINFOLOADER_H_
namespace GameInfoLoader {
static void Load() {
  GameSettings::Load(GAME_SETTINGS);
}
}  // namespace GameInfoLoader
#endif  //MAGEQUEST_SRC_GAMESTATEIO_LOADING_LOADERS_GAMEINFOLOADER_H_
