#ifndef MAGEQUEST_SRC_GAMESTATEIO_LOADING_LOADERS_MISCLOADER_H_
#define MAGEQUEST_SRC_GAMESTATEIO_LOADING_LOADERS_MISCLOADER_H_
namespace MiscLoader {
static void Load() noexcept {}
}  // namespace MiscLoader
#endif  //MAGEQUEST_SRC_GAMESTATEIO_LOADING_LOADERS_MISCLOADER_H_
